----------------------------------------------------------------------------------------------------------------
--初始化民族代码。
----------------------------------------------------------------------------------------------------------------
delete from tblDSIPeople
go

INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 01,1,N'汉族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 02,2,N'蒙古族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 03,3,N'回族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 04,4,N'藏族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 05,5,N'维吾尔族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 06,6,N'苗族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 07,07,N'彝族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 08,8,N'壮族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 09,9,N'布依族')

INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 10,10,N'朝鲜族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 11,11,N'满族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 12,12,N'侗族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 13,13,N'瑶族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 14,14,N'白族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 15,15,N'土家族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 16,16,N'哈尼族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 17,17,N'哈萨克族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 18,18,N'傣族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 19,19,N'黎族')

INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 20,20,N'傈僳族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 21,21,N'佤族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 22,22,N'畲族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 23,23,N'高山族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 24,24,N'拉祜族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 25,25,N'水族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 26,26,N'东乡族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 27,27,N'纳西族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 28,28,N'景颇族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 29,29,N'柯尔克孜')

INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 30,30,N'土族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 31,31,N'达斡尔族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 32,32,N'仫佬族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 33,33,N'羌族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 34,34,N'布朗族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 35,35,N'撒拉族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 36,36,N'毛难族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 37,37,N'仡佬族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 38,38,N'锡伯族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 39,39,N'阿昌族')

INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 40,40,N'普米族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 41,41,N'塔吉克族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 42,42,N'怒族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 43,43,N'乌孜别克')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 44,44,N'俄罗斯族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 45,45,N'鄂温克族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 46,46,N'崩龙族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 47,47,N'保安族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 48,48,N'裕固族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 49,49,N'京族')

INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 50,50,N'塔塔尔族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 51,51,N'独龙族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 52,52,N'鄂伦春族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 53,53,N'赫哲族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 54,54,N'门巴族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 55,55,N'珞巴族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 56,56,N'基诺族')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 97,97,N'其他')
INSERT [tblDSIPeople] ([PeopleID],[PeopleCode],[PeopleName]) VALUES ( 98,98,N'外国血统中国籍人士')