//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaesoft.DSI.Web {
    
    
    public partial class frmDSIEduAudit {
        
        /// <summary>
        /// vsfrmDSIEduAudit 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.ValidationSummaryEx vsfrmDSIEduAudit;
        
        /// <summary>
        /// lbCommitteeAllowance 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbCommitteeAllowance;
        
        /// <summary>
        /// txtCommitteeAllowance 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.TextBoxEx txtCommitteeAllowance;
        
        /// <summary>
        /// lbLeadershipAllowance 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbLeadershipAllowance;
        
        /// <summary>
        /// txtLeadershipAllowance 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.TextBoxEx txtLeadershipAllowance;
        
        /// <summary>
        /// lbFinalAllowance 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbFinalAllowance;
        
        /// <summary>
        /// txtFinalAllowance 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.TextBoxEx txtFinalAllowance;
        
        /// <summary>
        /// lbAuditStatus 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.LabelEx lbAuditStatus;
        
        /// <summary>
        /// rdAuditStatus 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.RadioButtonListEx rdAuditStatus;
        
        /// <summary>
        /// errMessage 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.ServerAlert errMessage;
        
        /// <summary>
        /// btnApproval 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.ButtonEx btnApproval;
        
        /// <summary>
        /// btnCancel 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::iPower.Web.UI.ButtonEx btnCancel;
    }
}
